[[redirects]]
  from = "/feed/*"
  to = "https://attendancetracker-backend.herokuapp.com/:splat"
  status = 200
  force = true
  
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"